name: dr_oftal_pro
description: Aplicativo de acuidade visual para TV Box / Fire Stick
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  provider: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
